Adding case sensitive option
biopet/replacecontigsgtffile pull request #4
Opened 2017-11-03 14:13 UTC by ffinfo

### Description

Adding case sensitive option

----

### Checklist (never delete this)

- [ ] Each method/class/object/trait should have scaladocs
- [ ] Added methods are unit tested
- [ ] Test coverage may not drop
- [ ] Documentation should be updated if required

2017-11-03 14:44 UTC, DavyCats requested changes
Case sensitivity is not tested

2017-11-03 18:19 UTC, ffinfo commented
@DavyCats: Good point, added an extra test. Good thing because there was still a bug in there ;)

2017-11-06 08:17 UTC, rhpvorderman approved these changes
:+1:  Documentation and tests. Very nice.

2017-11-06 08:18 UTC, DavyCats approved these changes

2017-11-06 08:18 UTC, merged